### ISSUE TITLE
pop up error informantion

### ISSUE THREAD

**Issue by haoglehaogle** [trac-hacks/trac-code-comments-plugin#55] opened 2015-04-27 07:31 UTC
Hello,

It always popup error dialog: "Not Found: Environment not found".
and comments's URL is not correct miss root path( such as, URL should be is "/project_1/file_c", but miss "/project_1/"
Thanks!

**Comment by schwuk** [comment] 2015-07-14 06:59
I believe this is a duplicate of #56 which has been fixed. Please confirm and reopen if necessary.

**Closed as completed by schwuk** 2015-07-14 06:59 UTC
